# Generated by Django 5.2.4 on 2025-07-14 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_nickname"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="email",),
    ]
