# Generated by Django 5.2.4 on 2025-07-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(default="default_nickname", max_length=30),
        ),
    ]
