version: '3'
services:
    web:
        image: server
        container_name: web
        command: bash -c "gunicorn movie_review.wsgi:application -b 0.0.0.0:8000" # 서버 실행
        ports:
            - '8000:8000'
        restart: always
        env_file:
            - .env # gpt로 추가
        volumes:
            - .:/app
            - ./static:/app/static
            - ./media:/app/media # media가 있으면
        networks:
            - server
    nginx:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
            # - ./static:/static
            # - ./media:/media # media가 있으면
            # - ./cert/certbot/conf:/etc/letsencrypt # 이 부분
            # - ./cert/certbot/www:/var/www/certbot # 이 부분
            # - ./cert/certbot/conf/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf # gpt로 이거 추가
            # - ./cert/certbot/conf/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem # 얘도 추가

        restart: always # 이 부분
        ports:
            - '80:80'
            - '443:443' # 이 부분
        depends_on:
            - web
        networks:
            - server
        ## ↓ 이 부분
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

    # 이 밑은 전부 다
    # certbot:
    #     image: certbot/certbot
    #     restart: unless-stopped
    #     volumes:
    #         - ./cert/certbot/conf:/etc/letsencrypt
    #         - ./cert/certbot/www:/var/www/certbot
    #     ## ↓ 이 부분
    #     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
    server:
