# Generated by Django 5.2.4 on 2025-07-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_remove_movie_age"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment", old_name="user", new_name="user_id",
        ),
    ]
